version: '3'
services:

  front:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    env_file:
      - .env
    restart: always
    depends_on:
      - front
    entrypoint: ["/nginx-entrypoint.sh"]
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./sh/nginx-entrypoint.sh:/nginx-entrypoint.sh
      - ./data/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
      - ../data/nginx/cache:/var/cache/nginx
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/dns-route53
    restart: always
    env_file:
      - .env
    volumes:
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --dns-route53 --dns-route53-propagation-seconds 30; sleep 12h & wait $${!}; done;'"
